### PR TITLE
Fix MISUSE error. It comes from uninitialized flag_count variable.

### PR DESCRIPTION
**Pull request by Shaienn**

### CODE REVIEW

**Comment by siscia** [comment]
@Shaienn definitely right, sorry about that...

**Comment by siscia** [comment]
@Shaienn did you use the code ? Does it actually works ?

**Comment by Shaienn** [comment]
Just started to implement :) Should works, why not?

**Comment by siscia** [comment]
Actually I didn't have the time nor the opportunity neither the necessity to use the code I wrote, the test runs just fine, but if you find bugs it is perfectly normal...

Really sorry about that...

**Pull request merged**
